apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: prometheus
    component: prometheus-server
  name: test-image
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
